FROM debian:jessie

MAINTAINER Eric Solberg "eric@tinkery.io"

# Update package manager
RUN apt-get update

# Install misc tools/packages
RUN apt-get -y install ca-certificates wget curl zip unzip gzip vim

# Setup git client

# Setup GCloud

# Setup Docker

# Create dev directory
ENV DEV_HOME /esol-dev
RUN mkdir $DEV_HOME

# Pull my dev tools from GitHub

# Setup path

WORKDIR $DEV_HOME
CMD ["bash"]
